name: CI/CD for ASP.NET MVC

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Build & Test ASP.NET App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      - name: Restore Dependencies
        run: dotnet restore SingNature/SingNature.sln

      - name: Build Application
        run: dotnet build SingNature/SingNature.sln --configuration Release --no-restore

      - name: Run Unit Tests
        run: dotnet test SingNature/SingNature.sln --configuration Release --no-restore --logger trx --results-directory TestResults

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: TestResults

  security_scan:
    name: Static Security Analysis (SAST)
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: csharp

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  dast_scan:
    name: Dynamic Security Analysis (DAST)
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - name: Install OWASP ZAP
        run: |
          sudo apt update
          sudo apt install zaproxy -y

      - name: Run DAST Scan
        run: |
          zap-cli quick-scan --start-options '-config api.disablekey=true' http://your-staging-url.com

#   deploy:
#     name: Deploy to DigitalOcean Droplet
#     runs-on: ubuntu-latest
#     needs: [build_and_test, security_scan, dast_scan]
    
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Setup .NET
#         uses: actions/setup-dotnet@v3
#         with:
#           dotnet-version: '9.0'

#       - name: Publish Application
#         run: |
#           dotnet publish SingNature/SingNature.sln -c Release -o publish

#       - name: Deploy to DigitalOcean
#         uses: appleboy/scp-action@v0.1.4
#         with:
#           host: ${{ secrets.DROPLET_IP }}
#           username: ${{ secrets.DROPLET_USER }}
#           key: ${{ secrets.DROPLET_SSH_KEY }}
#           source: "publish/"
#           target: "/var/www/singnature"

#       - name: Restart Application
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.DROPLET_IP }}
#           username: ${{ secrets.DROPLET_USER }}
#           key: ${{ secrets.DROPLET_SSH_KEY }}
#           script: |
#             sudo systemctl restart singnature
